apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type  }}
  selector:
    appName: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port  }}
      targetPort: {{ .Values.service.port  }}